"""Add pdf_path column

Revision ID: f8daaa48cdc9
Revises: 
Create Date: 2025-07-24 08:37:56.497962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8daaa48cdc9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('insurance_submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pdf_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('insurance_submissions', schema=None) as batch_op:
        batch_op.drop_column('pdf_path')

    # ### end Alembic commands ###
